services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - net

networks:
  net:
    driver: bridge